-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.16-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL version:             7.0.0.4152
-- Date/time:                    2012-07-01 23:04:24
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;
-- Dumping data for table frontend.catalogs: ~13 rows (approximately)
DELETE FROM `catalogs`;
/*!40000 ALTER TABLE `catalogs` DISABLE KEYS */;
INSERT INTO `catalogs` (`id`, `catname`, `alias`, `catdesc`, `parent_id`, `date`, `status`, `intrash`) VALUES
	(1, 'Каталог номер 1', 'catalog1', 'Описание каталога номер 1', 0, '2012-06-20', 1, 0),
	(2, 'Каталог номер 2', 'catalog2', 'Описание каталога номер 2', 1, '2012-06-20', 1, 0),
	(3, 'Каталог номер 3', 'catalog3', 'Описание каталога номер 3', 1, '2012-06-20', 1, 0),
	(5, 'Каталог номер 4', 'catalog4', 'Описание каталога номер 4', 1, '2012-06-14', 1, 0),
	(6, 'Каталог номер 5', 'catalog5', 'Описание каталога номер 5', 2, '2012-06-14', 1, 0),
	(7, 'Каталог номер 6', 'catalog6', 'Описание каталога номер 6', 2, '2012-06-16', 0, 0),
	(8, 'Каталог номер 7', 'catalog7', 'Описание каталога номер 7', 2, '2012-06-16', 0, 0),
	(9, 'Каталог номер 8', 'catalog8', 'Описание каталога номер 8', 2, '2012-06-21', 0, 0),
	(10, 'Каталог номер 9', 'catalog9', 'Описание каталога номер 9', 2, '2012-06-09', 0, 0),
	(11, 'Каталог номер 10', 'catalog10', 'Описание каталога номер 10', 2, '2012-06-02', 1, 0),
	(12, 'Каталог номер 11', 'catalog11', 'Описание каталога номер 11', 2, '2012-06-15', 1, 0),
	(13, 'Каталог номер 12', 'catalog12', 'Описание каталога номер 12', 2, '2012-06-30', 1, 0),
	(14, 'Каталог номер 13', 'catalog13', 'Описание каталога номер 13', 2, '2012-06-30', 1, 0);
/*!40000 ALTER TABLE `catalogs` ENABLE KEYS */;

-- Dumping data for table frontend.mails: ~1 rows (approximately)
DELETE FROM `mails`;
/*!40000 ALTER TABLE `mails` DISABLE KEYS */;
INSERT INTO `mails` (`id`, `to`, `subject`, `from`, `message`, `date`) VALUES
	(1, 'dima.shustoff@gmail.com', 'hello', 'admin@admin.ru', 'tryam!!!', '2012-06-27');
/*!40000 ALTER TABLE `mails` ENABLE KEYS */;

-- Dumping data for table frontend.modules: ~3 rows (approximately)
DELETE FROM `modules`;
/*!40000 ALTER TABLE `modules` DISABLE KEYS */;
INSERT INTO `modules` (`id`, `name`, `systemname`, `content`, `user_id`, `type`, `date`, `status`, `intrash`) VALUES
	(2, 'Модуль навигации', 'navigation', 'Описание модуля навигации', 1, 'HTML', '2012-06-16', 1, 0),
	(3, 'Модуль валидации', 'validation', 'Описание модуля валидации', 1, 'PHP', '2012-06-16', 1, 0),
	(5, 'Модуль пагинации', 'pagination', 'Описание модуля пагинации', 1, 'JS', '2012-06-16', 1, 0);
/*!40000 ALTER TABLE `modules` ENABLE KEYS */;

-- Dumping data for table frontend.options: ~1 rows (approximately)
DELETE FROM `options`;
/*!40000 ALTER TABLE `options` DISABLE KEYS */;
INSERT INTO `options` (`id`, `sitename`, `description`, `keywords`, `robots`, `email`, `email_from`, `copyright`, `page404`, `status`, `htaccess`, `debug`, `cache`, `session`) VALUES
	(1, 'Имя сайта', 'Описание сайта', 'ключевые, слова, тут', 0, 'admin@example.ru', 'Вася Пупкин', 'Все права никому не принадлежат.', 'Запрошенная вами страница на существует.', 1, 0, 0, 0, 65);
/*!40000 ALTER TABLE `options` ENABLE KEYS */;

-- Dumping data for table frontend.pages: ~18 rows (approximately)
DELETE FROM `pages`;
/*!40000 ALTER TABLE `pages` DISABLE KEYS */;
INSERT INTO `pages` (`id`, `pagename`, `alias`, `metadesc`, `metakeywords`, `content`, `catalog_id`, `author_id`, `date`, `status`, `intrash`) VALUES
	(1, 'Супер страница 1', 'super-stranica-1', 'Это описание супер страницы номер 1 ', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-20', 1, 0),
	(6, 'страница 20', 'page2', 'описание страницы номер 20', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-22', 1, 0),
	(7, 'страница 21', 'page3', 'описание страницы номер 20', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-22', 1, 0),
	(8, 'страница 22', 'page3', 'описание страницы номер 22', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-22', 1, 0),
	(9, 'страница 23', 'page3', 'описание страницы номер 23', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-22', 1, 0),
	(10, 'страница 24', 'page3', 'описание страницы номер 24', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-18', 1, 0),
	(11, 'страница 30', 'page3', 'Описание страницы 30', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-23', 1, 0),
	(12, 'страница 31', 'page3', 'Описание страницы 30', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-23', 1, 0),
	(13, 'страница 32', 'page3', 'Описание страницы 30', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-29', 1, 0),
	(14, 'страница 33', 'page3', 'Описание страницы 33', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-18', 1, 0),
	(15, 'страница 34', 'page4', 'Описание страницы 34', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-28', 1, 0),
	(16, 'страница 35', 'page4', 'Описание страницы 34', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-15', 1, 0),
	(17, 'страница 35', 'page4', 'Описание страницы 34', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-22', 1, 0),
	(18, 'страница 35', 'page4', 'Описание страницы 34', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-23', 1, 0),
	(19, 'страница 35', 'page5', 'Описание страницы 35', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-22', 1, 0),
	(20, 'страница 36', 'page6', 'Описание страницы 36', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-22', 1, 0),
	(21, 'Страница 2', 'page222', 'Описание страницы 2', 'ключевые слова, слова ключевые, словечки', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla nibh quis odio sagittis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut et odio neque, at accumsan ipsum. Phasellus ac bibendum massa. Donec egestas erat quis nunc consectetur scelerisque pretium tortor tristique. Suspendisse id diam ac ante ultricies convallis. Curabitur imperdiet porttitor est non scelerisque. Sed condimentum adipiscing ligula nec mollis. Nam risus nisi, pharetra nec rutrum quis, venenatis quis felis. Vivamus porta, turpis ut tempus pretium, erat mauris egestas nibh, eu tincidunt ante odio ac metus. Fusce tortor purus, vulputate et malesuada in, vehicula quis tellus. Nullam vestibulum ligula at nunc vulputate sit amet pulvinar nunc sollicitudin. Vestibulum dignissim placerat metus, in pellentesque odio viverra in.</p>\r\n\r\n<p>Vivamus rhoncus ultricies massa in sodales. Quisque ac purus nec nisl iaculis viverra. Praesent aliquet mauris a risus aliquet non suscipit nisi hendrerit. Fusce eu scelerisque eros. Pellentesque id eros in nisi aliquet malesuada. Morbi sodales tristique dictum. In hac habitasse platea dictumst. Integer vestibulum urna a tortor sollicitudin sit amet pharetra erat semper. Morbi eros quam, mattis non pellentesque a, ornare non risus. Duis accumsan dolor eget dui pharetra eu pharetra diam congue. Maecenas facilisis feugiat metus nec malesuada.</p>\r\n\r\n<p>Curabitur eget rutrum tortor. Duis eleifend libero ut dui sodales ullamcorper. Pellentesque commodo, arcu vel bibendum volutpat, velit eros dignissim lectus, eu egestas nunc sapien id dui. Curabitur ornare, velit vel imperdiet scelerisque, massa arcu commodo lacus, ac pellentesque urna nibh nec quam. Phasellus cursus ultrices scelerisque. Praesent magna leo, iaculis in pellentesque nec, volutpat ac massa. Nullam rhoncus consectetur rhoncus. Donec vel ultricies velit. Nam nec cursus lectus. Sed porta quam a sapien elementum quis volutpat lorem elementum. Phasellus eu feugiat ipsum. Nulla pretium magna in urna rutrum dignissim. Integer porta justo vitae sapien congue laoreet. Quisque ac lacus dolor. </p>', 1, 1, '2012-06-14', 1, 0);
/*!40000 ALTER TABLE `pages` ENABLE KEYS */;

-- Dumping data for table frontend.roles: ~3 rows (approximately)
DELETE FROM `roles`;
/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
INSERT INTO `roles` (`id`, `name`, `description`, `pages`, `cats`, `users`, `mods`, `mails`, `stats`, `opts`, `trash`) VALUES
	(1, 'login', 'Зарегистрированный', 0, 0, 0, 0, 0, 0, 0, 0),
	(2, 'admin', 'Администратор', 1, 1, 1, 1, 1, 1, 1, 1),
	(3, 'manager', 'Манагер', 1, 1, 0, 0, 1, 0, 0, 1);
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;

-- Dumping data for table frontend.roles_users: ~3 rows (approximately)
DELETE FROM `roles_users`;
/*!40000 ALTER TABLE `roles_users` DISABLE KEYS */;
INSERT INTO `roles_users` (`user_id`, `role_id`) VALUES
	(1, 1),
	(10, 1),
	(1, 2),
	(10, 3);
/*!40000 ALTER TABLE `roles_users` ENABLE KEYS */;

-- Dumping data for table frontend.users: ~2 rows (approximately)
DELETE FROM `users`;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `email`, `username`, `password`, `firstname`, `lastname`, `datereg`, `status`, `logins`, `last_login`, `intrash`) VALUES
	(1, 'admin@admin.ru', 'admin', 'ac6f6788b30fa58d5fbddad35140bad44b0ce132dec42bf54f160f1ac451722d', 'Dima', 'Shustov', '2012-06-28', 1, 39, 1341168777, 0),
	(10, 'dima116@rambler.ru', 'man', 'ac6f6788b30fa58d5fbddad35140bad44b0ce132dec42bf54f160f1ac451722d', 'asdsad', 'adad', '2012-07-04', 1, 5, 1341168880, 0);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

-- Dumping data for table frontend.user_tokens: ~0 rows (approximately)
DELETE FROM `user_tokens`;
/*!40000 ALTER TABLE `user_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `user_tokens` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
